# Source for original workflow creator: https://www.youtube.com/watch?v=gIHBVpJhmEk
name: Deploy api to Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_API_ID }}
on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - "api-database/**"
      
jobs:
  deploy:
    if: github.repository == 'cs421sp25-homework/team-10'
    runs-on: ubuntu-latest
    steps:
      - name: Install jest
        run: npm install
      - name: Run Jest tests
        run: npm test
      - uses: actions/checkout@v4
      - name: Install jest
        run: npm install
      - name: Run Jest tests
        run: npm test
      - name: install Vercel CLI
        run: npm install --global vercel@latest
      - name: Change directory, pull vercel info, then deploy that john
        run: |
          cd api-database/
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
