# Source for original workflow creator: https://www.youtube.com/watch?v=gIHBVpJhmEk
name: Deploy api to Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_API_ID }}
 

on:
  push:
    branches:
      - master

  workflow_dispatch:
  workflow_call:

  release:
    types: [published]

      
jobs:

  run_jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies in web and api database
        env:
         TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
        run: |
          npm install -g pnpm
          pnpm install
          cd web/
          npm install -g pnpm
          pnpm install
          cd ..
          cd api-database
          npm install -g pnpm
          pnpm install
      - name: Install jest
        run: pnpm install
      - name: Run Jest tests
        run:  TEST_DB_URL=${{ secrets.TEST_DB_URL }} pnpm test
             
      - name: install Vercel CLI
        run: npm install --global vercel@latest
      - name: Change directory, pull vercel info, then deploy that john
        run: |
          cd api-database/
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}            