name: Cypress Tests
on: [push]
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2

     - name: Move files in the "web" folder to the root
       run: |
         ls -lah
         shopt -s dotglob
         mv web/* .
         rm -rf web
         ls -lah
 
     - name: Run Cypress Test
       uses: cypress-io/github-action@v4
       with:
         command: cd web && npx cypress run
         browser: chrome