name: Cypress Tests

on: push
      
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        

      - name: Run cypress tests
        run: |
          cd api-database/
          npm install -g pnpm
          npm install
          pnpm install
          npm install -g wait-on
          pnpm dev & wait-on http://localhost:3000

          cd web/
          npm install -g pnpm
          npm install
          npm install --save-dev cypress
          pnpm install
          npm install -g wait-on
          pnpm dev & wait-on http://localhost:5173
          npx cypress run