name: Cypress Tests

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEB_ID }}
  VITE_API_DB_URL: http://localhost:3000
  VITE_API_MACHINE_URL: http://localhost:5000
  VITE_BASE_URL: http://localhost:5173
  TEST_DB_URL: ${{ secrets.DATABASE_CREDENTIALS }}

on: 
  workflow_call:
      
jobs:
  
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run local host api
        run: |
          cd api-database/
          npm install -g pnpm
          pnpm install
          pnpm dev &
      - name: Run local host web
        run: |
          cd web/
          npm install -g pnpm
          npm install --save-dev cypress
          pnpm install

          pnpm dev & wait-on http://localhost:5173/
      - name: Run cypress tests
        run: |
          cd web/
          npx cypress run