name: Cypress Tests

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEB_ID }}
  VITE_API_DB_URL: http://localhost:3000
  VITE_API_MACHINE_URL: http://localhost:5000
  VITE_BASE_URL: http://localhost:5173
  DATABASE_URL: ${{ secrets.DATABASE_CREDENTIALS }}
  TEST_DB_URL: ${{ secrets.TEST_DB_URL }}

on: 
  workflow_call:
      
jobs:
  cypress-run:
    container: cypress/included:14.3.2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm install
          cd api-database
          pnpm install
          cd ../web
          pnpm install
          cd ..

      - name: do API & Web & run Cypress
        run: |
          cd api-database
          pnpm dev &       
          cd ../web
          pnpm dev &       
          cd ..
      
          cd web
          npx cypress run