name: Cypress Tests

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEB_ID }}
  VITE_API_DB_URL: http://localhost:3000
  VITE_API_MACHINE_URL: http://localhost:5000
  VITE_BASE_URL: http://localhost:5173
  DATABASE_URL: ${{ secrets.DATABASE_CREDENTIALS }}
  TEST_DB_URL: ${{ secrets.TEST_DB_URL }}

on: 
  workflow_call:
      
jobs:
  
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/included:14.3.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run local host api
        run: |
          cd api-database/
          npm install -g pnpm
          npm install 
          pnpm install
          pnpm dev &

      - name: Run local host web
        run: |
          cd web/
          npm install -g pnpm
          pnpm install 
          pnpm add -D cypress
          npm install -g wait-on 
          pnpm dev & wait-on http://localhost:5173/
     
      - name: run cypress tests
        run: |
          cd web/
          npx cypress run