name: Cypress Tests

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEB_ID }}
  VITE_API_DB_URL: http://localhost:3000
  VITE_API_MACHINE_URL: http://localhost:5000
  VITE_BASE_URL: http://localhost:5173
  DATABASE_URL: ${{ secrets.DATABASE_CREDENTIALS }}



on: push
      
jobs:
  
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run local host api
        run: |
          cd api-database/
          npm install -g pnpm
          npm install
          pnpm install
          npm install -g wait-on
          pnpm dev &

      - name: Run local host apweb
        run: |
          cd web/
          npm install -g pnpm
          npm install
          npm install --save-dev cypress
          pnpm install
          pnpm dev &

      - name: Run cypress tests
        run: |
          cd web/
          npx cypress run