name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run local host
        run: |
          cd web/
          npm install -g pnpm
          pnpm install
          pnpm add --save-dev cypress
          npm install -g wait-on
          pnpm dev & wait-on http://localhost:5173
          npx Cypress run
      - name: Run cypress tests
        run: |
          cd web/
          npm install -g pnpm
          npx Cypress run

          if: steps.detect-package-manager.outputs.manager == 'pnpm'
