name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cyprus
        run: |
          cd web/
          npm install cypress --save-dev
          npx Cypress run

