name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cyprus
        run: |
          cd web/
          npm install -g pnpm
          pnpm add --save-dev cypress
          pnpm install
          pnpm dev
          npx Cypress run

          if: steps.detect-package-manager.outputs.manager == 'pnpm'
