name: Jest

on: 
  workflow_call:
  push:


jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies in web and api database
        run: |
          npm install -g pnpm
          pnpm install
          cd web/
          npm install -g pnpm
          pnpm install
          cd ..
          cd api-database
          npm install -g pnpm
          pnpm install
      - name: Install jest
        run: pnpm install
      - name: Run Jest tests
        run: pnpm test
