name: Jest

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEB_ID }}
  VITE_API_DB_URL: http://localhost:3000
  VITE_API_MACHINE_URL: http://localhost:5000
  VITE_BASE_URL: http://localhost:5173
  TEST_DB_URL: ${{ secrets.TEST_DB_URL }}

on: 
  workflow_call:
  push:


jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies in web and api database
        run: |
          npm install -g pnpm
          pnpm install
          cd web/
          npm install -g pnpm
          pnpm install
          cd ..
          cd api-database
          npm install -g pnpm
          pnpm install
      - name: Install jest
        run: pnpm install
      - name: Run Jest tests
        run: pnpm test
