name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: team_EjOoxtsIQ8YZy8Q7qnD0fo2J
  VERCEL_PROJECT_ID: prj_M8Sq239pU97i1Y9UUszfmVT0XgHf
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: pnpm i -g vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=Pi4jtZoRixlf4YXvqnUDkgqv 
      - name: Build Project Artifacts
        run: vercel build --token=Pi4jtZoRixlf4YXvqnUDkgqv
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=Pi4jtZoRixlf4YXvqnUDkgqv
