# Source for original workflow creator: https://www.youtube.com/watch?v=gIHBVpJhmEk
name: Deploy web to Vercel and test
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEB_ID }}
  TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
  VITE_API_DB_URL: http://localhost:3000
  VITE_API_MACHINE_URL: http://localhost:5000
  VITE_BASE_URL: http://localhost:5173
  DATABASE_URL: ${{ secrets.DATABASE_CREDENTIALS }}
  
on:
  workflow_dispatch:
  workflow_call:
  push:

  release:
    types: [published]
      
jobs:

  deploy:
    container: cypress/included:14.3.2
    if: github.repository == 'cs421sp25-homework/team-10'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Change directory, install vercel CLI, pull environment, then deploy that john.
        run: |
          cd web/
          npm install -g pnpm
          pnpm install
          npm install --global vercel@latest
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --token=${{ secrets.VERCEL_TOKEN }} --force
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --force

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm install
          cd api-database
          pnpm install
          cd ../web
          pnpm install
          cd ..

      - name: do API & Web & run Cypress
        run: |
          cd api-database
          pnpm dev &       
          cd ../web
          pnpm dev &       
          cd ..
      
          cd web
          npx cypress run
          


