# Source for original workflow creator: https://www.youtube.com/watch?v=gIHBVpJhmEk
name: Deploy web to Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEB_ID }}
on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - "web/**"
      
jobs:
  deploy:
    if: github.repository == 'cs421sp25-homework/team-10'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run cypress tests
        run: |
          cd web/
          npm install -g pnpm
          npm install
          npm install --save-dev cypress
          pnpm install
          npm install -g wait-on
          pnpm dev & wait-on http://localhost:5173
          npx cypress run

      - name: Install dependencies in web and api database
        run: |
            cd web/
            npm install -g pnpm
            npm install
            pnpm install
            cd ..
            cd api-database
            npm install -g pnpm
            npm install
            pnpm install
  
      - name: Install jest
        run: npm install
      - name: Run Jest tests
        run: npm test
        
      - name: Change directory, install vercel CLI, pull environment, then deploy that john.
        run: |
          cd web/
          npm install --global vercel@latest
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}            