# Source for original workflow creator: https://www.youtube.com/watch?v=gIHBVpJhmEk
name: Deploy web to Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEB_ID }}
on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - "web/**"
      
jobs:
  deploy:
    if: github.repository == 'cs421sp25-homework/team-10'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

    # Install npm dependencies, cache them correctly
    # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: |
            cd web/
            npm run build
          start: |
            cd web/
            npm start


      - name: Install jest
        run: npm install

      - name: Run Jest tests
        run: npm test
        
      - name: Change directory, install vercel CLI, pull environment, then deploy that john.
        run: |
          cd web/
          npm install --global vercel@latest
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}            