# Source for original workflow creator: https://www.youtube.com/watch?v=gIHBVpJhmEk
name: Deploy web to Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEB_ID }}
on:

  workflow_dispatch:
  workflow_call:

  release:
    types: [published]
      
jobs:

  deploy:
    if: github.repository == 'cs421sp25-homework/team-10'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
          
      - name: Change directory, install vercel CLI, pull environment, then deploy that john.
        run: |
          cd web/
          npm install --global vercel@latest
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --token=${{ secrets.VERCEL_TOKEN }} --force
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --force         